spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: embarkx
    password: embarkx

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
